branches:
  - master
  - name: next
    prerelease: true

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - '@semantic-release/npm'
  - '@semantic-release/github'

repositoryUrl: https://github.com/tarik02/run-linters
