name: check

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: jdx/mise-action@v2

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile

      - name: Lint
        run: |
          bun run lint
