name: default

on:
  workflow_dispatch:
  push:
    branches:
      - '**'

permissions:
  contents: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  default:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: jdx/mise-action@v2

      - name: Install dependencies
        run: |
          bun install --frozen-lockfile

      - name: Build
        run: |
          bun run build

      - if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next' }}
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next' }}
        name: Semantic Release
        run: |
          bun run semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
