name: create pr from next to master

on:
  workflow_dispatch:
  push:
    branches: [next]

jobs:
  next-pr:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Fetch default branch
        run: |
          git fetch origin ${{ github.event.repository.default_branch }} --depth 1

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create Pull Request
        run: |
          if [[ "$(git rev-parse "origin/$DEFAULT_BRANCH")" != "$(git rev-parse origin/next)" ]]; then
            PR_URL="$(gh pr list --base "$DEFAULT_BRANCH" --head next --state open --limit 1 --json url --jq .[].url)"
            if [[ -z "${PR_URL}" ]]; then
              gh pr create -B "$DEFAULT_BRANCH" -H next --title "merge next to $DEFAULT_BRANCH" --body ''
            fi
          fi
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
